### ISSUE TITLE
onGroupTransaction

### ISSUE THREAD

**Issue by Neztore** [noblox/noblox.js#307]
# Steps:
1. Add shortPoll method like the other events
2. Make getGroupTransaction return a bluebird promise

Also should we consider stopping using bluebird given how widely used native promises are?
Either way I think we need a consistent approach where it's either **always** a bluebird promise, or **always** a native promise - instead of a mixture.

**Comment by BillyH-0167** [comment]
There isnt a onGroupTransaction in noblox.js repo, Unless its planned to be added?

**Comment by colenh** [comment]
> There isnt a onGroupTransaction in noblox.js repo, Unless its planned to be added?

pretty sure he's recommending the addirion of one

**Comment by FxllenCode** [comment]
Hey, is there a status update on this? This is huge for me, I could really use this right now!
