### ISSUE TITLE
Adding a getGroupPending Function

### ISSUE THREAD

**Issue by tthomxs** [noblox/noblox.js#333]
## Noblox.js Suggestion

**Why it should be added?**
I think this feature would be useful because it can be used in many ways from statistics to group features. It is something that the [ROBLOX API](https://economy.roblox.com/v1/groups/${GroupID}/revenue/summary/${DAY/WEEK/MONTH/YEAR}) already supports.

**API**
https://economy.roblox.com/v1/groups/${GroupId}/revenue/summary/${Optional} Choice - Default is Day
Day 
Week
Month
Year

Thanks! 😄

**Comment by alanbixby** [comment]
I'm not a fan of the name `getGroupPending()`, as that can get confused with a number of other 'pending' things, however I can see the utility in adding a `getGroupRevenueSummary()`.

In the meantime, you can mimic this functionality in `noblox.js` using [`getGroupTransactions()`](https://noblox.js.org/global.html#getGroupTransactions). The endpoint returns the individualized transactions, which have an attribute `isPending`. Page through the results til you get `isPending = false` and add up all the transactions.
