### ISSUE TITLE
Add displayName to typings and test cases

### ISSUE THREAD

**Issue by alanbixby** [noblox/noblox.js#373]
It appears `displayName`s are enabled globally; as such many endpoints include a `displayName` proprerty however our library does not accurately reflect this.

I would strongly advise updating our unit tests in addition to our typings to avoid issues such as #372, where types were added but our code artificially excluded `displayName`.

---

Resources such as [jkmdev's API tracker](https://github.com/Roblox-Trackers/Roblox-API-Tracker) should aid in this effort, using `git grep displayName` to show all additions of `displayName`, but we will still need to manually check all of the undocumented endpoints (economy, www, etc).

**Comment by Neztore** [comment]
```
Auth/Auth v1
Auth/Auth v2
Auth/Auth v2
Badges/Badges v1
Badges/Badges v1
Chat/Chat v2
Chat/Chat v2
Develop/Develop v1
Develop/Develop v1
Friends/Friends v1
Friends/Friends v1
Friends/Friends v1
Friends/Friends v1
Games/Games v1
Games/Games v1
Games/Games v1
Groups/Groups v1
Groups/Groups v1
Groups/Groups v2
Inventory/Inventory v1
Inventory/Inventory v1
Locale/Locale v1
PrivateMessages/PrivateMessages v1
Trades/Trades v1
Users/Users v1
Users/Users v1
Users/Users v1
Users/Users v1
Users/Users v1
Users/Users v1
```
