### ISSUE TITLE
Send Ally Request

### ISSUE THREAD

**Issue by nuthiom** [noblox/noblox.js#387]
I was going to see if we can have a feature where we can send an ally request. The parameters would be: groupId (The group that you want to send the request from,) groupRelationshipType ("enemies" or "allies,") and relatedGroupId (the group that you want to send the request to.) Of course roblox already has an api for this: [https://groups.roblox.com/docs#!/Relationships/post_v1_groups_groupId_relationships_groupRelationshipType_relatedGroupId](url) Please add this <3

**Comment by Neztore** [comment]
Could you describe a potential use-case for this feature?
