### ISSUE TITLE
[HELP NEEDED] 400 The request is invalid.

### ISSUE THREAD

**Issue by pineappledocs** [noblox/noblox.js#390]
So I am trying to check if the user is in the group id listed or not. Here is my code:

```js
    rbx.getBlurb(foundId).then(async blurb => { // Checks the blurb
             
                
              if(status.includes(newString) || blurb.includes(newString)) { // If code is in blurb procceds with operation
                const verified = new Discord.MessageEmbed()
  .setColor("GREEN")
  .setTitle("Prompt")
  .setDescription("You have now been verified! Please wait shortly as you are going to recieve the Verified role.")
  .setFooter("Verifying..")
  .setTimestamp() 
                 msg.channel.send(verified) // Sent if user has put code
                let group = 10894479
                let groups = await rbx.getGroups(names)
                
                  console.log(groups)
                if(!groups.find(g => g.Id === group)) {
                    message.channel.send('not in group')
                } else {
                    message.channel.send('in the group')
                } message.member.roles.add(message.guild.roles.cache.find(r => r.name == "new rolet")) // Add the users role
                message.member.setNickname(m.content) // Sets the users nickname
```

The error comes from the getGroups part, and I tried that code only, and it works though. I'm not sure the error though, and this is the error: Unhandled rejection Error: 400 The request is invalid.

How do I fix it?

**Comment by Neztore** [comment]
Hi There!
The code you have provided does not define `foundId`, nor `names`.
I suggest you ensure these are defined by logging their values.

[getGroups](https://noblox.js.org/global.html#getGroups) accepts a user id. If your variable is called `names` I suspect that is not what you are passing to it. You may also want to join [our discord](https://discord.com/invite/R5GVSyTVGv) - hope this helps!
