### ISSUE TITLE
[BUG] handleJoinRequest CSRF error

### ISSUE THREAD

**Issue by Creeper-pixel** [noblox/noblox.js#399]
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

**Describe the bug**
Cannot get csrf you are not logged in while trying to use handleJoinRequest()

**To Reproduce**
Basically i made a noblox.js auto ranking system and this just happens it has never happened to me before

**Expected behavior**
Im expecting for it to work properly

**Screenshots**
https://i.imgur.com/kHqZsNI.png

**Comment by policetonyR** [comment]
Your token is probably expired. Try getting a new one and setcookieing with it

**Comment by Creeper-pixel** [comment]
> Your token is probably expired. Try getting a new one and setcookieing with it

it is not but ok i'll try

**Comment by Creeper-pixel** [comment]
> Your token is probably expired. Try getting a new one and setcookieing with it

didnt work

**Comment by policetonyR** [comment]
Did you make sure to not click the logout button when grabbing the cookie?

**Comment by Creeper-pixel** [comment]
> Did you make sure to not click the logout button when grabbing the cookie?

yes i did

**Comment by Neztore** [comment]
Can we see some code? This is likely due to misuse of setCookie & the promise it returns.

**Comment by Creeper-pixel** [comment]
> Can we see some code? This is likely due to misuse of setCookie & the promise it returns.

`js
const Discord = require("discord.js");
const noblox = require('noblox.js')
module.exports.run = async (bot, message, args) => {

const cookie = process.env['cookie']

const fetch = require('node-fetch')
try {
fetch(`https://api.roblox.com/users/get-by-username?username=${args}`)
    .then(res => res.json())
    .then(json => {
      noblox.setCookie('cookie')
        noblox.handleJoinRequest(6486607, json.Id, true)
        message.channel.send('success')
    });
  }
catch (e) {
  message.channel.send('An error occured')
  console.log(e)
}
}
module.exports.help = {
  name:"whitelist"
}
`

**Comment by Neztore** [comment]
noblox.setCookie returns a `Promise`. You need to either `await` it, or handle the promise so that it resolves before you try to call other methods.

See the [Promises tutorial](https://noblox.js.org/tutorial-Promises.html).
