### ISSUE TITLE
Socket Hang Up on onShout [BUG]

### ISSUE THREAD

**Issue by conman0552** [noblox/noblox.js#431]
![image](https://user-images.githubusercontent.com/24281023/134835542-9eeb66cb-e69e-45d1-a767-087c640498d7.png)
Attached is the image of the issue that keeps reoccurring. After this issue is thrown. the bot no longer polls the server.

It looks like getShout is handling the error fine, but onShout.js at line 48 is missing a .catch statement, which it should have given that it's possible for getShout to reject the promise.

To reproduce, all I've needed to do is run noblox with the onShout event, and let it sit. After a bit the error pops up.

**Comment by conman0552** [comment]
After going through the code, it looks like [this issue](https://github.com/noblox/noblox.js/issues/429) is also caused potentially by the same thing, no error catching in the shortpoll. If I had to guess anything that uses shortpoll is probably effected.

**Comment by Neztore** [comment]
Code?
