### ISSUE TITLE
Change rank failed: bodyObject.filter is not a function

### ISSUE THREAD

**Issue by blorbee** [noblox/noblox.js#439]
im trying to run the promote command through roblox and i get that error im using version 4.12.0

`s.Promote(groupid, tonumber(args[1]))` -- thats the code to call the promote module

```lua
local function Request(Function, RequestBody)
	RequestBody["auth_key"] = Configs.AUTH_KEY

	local response = HttpService:RequestAsync(
		{
			Url = Configs.BaseUrl..Function, 
			Method = "POST",
			Headers = {
				["Content-Type"] = "application/json"
			},
			Body = HttpService:JSONEncode(RequestBody)
		}
	)

	if response.Success then
		print("Status code:", response.StatusCode, response.Body)
		print("Response body:\n", response.Body)

		return response.Body
	else
		print("The request failed:", response.StatusCode, response.Body)
		return response.Body
	end
end
```
code to request to the server

```lua
Server.Promote = function(GroupId, UserId)
	assert(typeof(GroupId) == "number", "Error: GroupId must be an integer")
	assert(typeof(UserId) == "number", "Error: UserId must be an integer")

	local Body = {
		Group = GroupId;
		Target = UserId;
	}

	local Success, Result = pcall(function()
		return Request('Promote', Body)
	end)

	print(Result)
end
```
promote code

AUTH_KEY is random numbers
BaseUrl is the url to the server which is just the url for my replit 

im following this tutorial for it: https://devforum.roblox.com/t/how-to-create-a-rank-management-system-using-glitch/442725/238

**Comment by Brandong04** [comment]
Not sure if this issue should be [here](https://github.com/noblox/noblox.js-server) instead, based on the fact that you aren’t using the node package for this, and using lua. 

However, from what I’ve heard and seen before surrounding this error, you might be providing a wrong value in your request body. So I’d double check your userID and groupID variables to make sure they are valid.

**Comment by Neztore** [comment]
I believe noblox.js-server relies on an out-of-date version of Noblox.js.
This bug was fixed with Noblox in the past. Try updating noblox.js - I will also open a PR to update it on the server master.
