### ISSUE TITLE
[BUG] nobles.uploadModel not working?

### ISSUE THREAD

**Issue by Unstable0** [noblox/noblox.js#457]
When I tried doing noblox.uploadModel(), It gave me this error `Error: Upload failed, confirm that all item options, asset options, and upload data are valid.`

I wanted it to upload my .rbxmx file but it didn't work

this is my code

```
const response = await noblox.uploadModel(fs.readFileSync("folder.rbxmx"), {
    name: "Test",
    description: "Cool",
    copyLocked: false,
    allowComments: false
});
```

the .rbxmx is not corrupted and it's in the directory

![Screen Shot 2564-11-03 at 8 41 58 PM](https://user-images.githubusercontent.com/46888825/140070948-d1f9c22f-32a1-4578-b352-15d10b7ee87e.png)

**Comment by Unstable0** [comment]
[folder.rbxmx.zip](https://github.com/noblox/noblox.js/files/7467967/folder.rbxmx.zip)

this is my file

**Comment by AlexFerrero** [comment]
Was your issue solved?

**Comment by Unstable0** [comment]
its solved
