### ISSUE TITLE
Discord > Roblox Game Client Interaction

### ISSUE THREAD

**Issue by Aerosphia** [noblox/noblox.js#471]
it would be awesome if we could get an api function that then executes code in a roblox place.

use case: remote banning, kicking, shutting down, etc from discord.

not asking for premade commands, just something that fires a server-made function in our roblox place - like an event
configuration on both ends would be required, so a tutorial would be needed

**Comment by Neztore** [comment]
This library is a web API wrapper. We provide a simple, consistent interface to interact with Roblox's web API.

As a result, this suggestion is out of scope. Please look into a different library - or create your own!
