### ISSUE TITLE
Support API keys (Open cloud)

### ISSUE THREAD

**Issue by Neztore** [noblox/noblox.js#473]
- Some new APIs have been added, and some have been modified to support these new OAuth based API keys.
- We should aim to phase out use of cookies and move to these new tokens, in preparation for when more APIs are made available

I would propose having a dual system, where all supported methods are moved to the new key system and all other APIs labelled as 'legacy' and using the cookie.
It may be worth making this v5 and continuing to maintain v4 of methods which use the current APIs.

At present only publish is available but this provides a good starting point.

**Comment by suufi** [comment]
partially implemented

**Comment by Neztore** [comment]
No longer planned
