### ISSUE TITLE
Display Name

### ISSUE THREAD

**Issue by IHZAQSTORM33** [noblox/noblox.js#487]
I love this package but can you make a function that return user display name from id,
Thanks

**Comment by Neztore** [comment]
See [getPlayerInfo(https://noblox.js.org/global.html#getPlayerInfo)], which returns a promise to a PlayerInfo object. PlayerInfo contains the key displayName.

**Comment by IHZAQSTORM33** [comment]
> See [getPlayerInfo](https://noblox.js.org/global.html#getPlayerInfo), which returns a promise to a PlayerInfo object. PlayerInfo contains the key displayName.

Damn its work
Noice
