### ISSUE TITLE
[BUG] onJoinRequestHandle does not behave as is documented

### ISSUE THREAD

**Issue by Aerosphia** [noblox/noblox.js#488]
Currently using this excerpt of code as an event handler for `onJoinRequestHandle`:
```js
// Special Event Handler
(async () => {
    await noblox.setCookie(process.env.cookie).catch(console.error);
    const onJoinRequestHandle = require(`../src/events/onJoinRequestHandle`);

    noblox.onJoinRequestHandle(config.group).on("data", (...args) => onJoinRequestHandle(mongoClient, ...args));
})().catch(console.error);
```

Receiving some issues though. This doesn't seem to fire unless I restart my hosting process. When restarting my hosting process, it fires for all members pending a join request (immediately), but never continues to do so until I restart again.

This may or may not be an internal issue, but I received a bit of confirmation [here](https://discord.com/channels/797610307928326194/797610307928326199/922994710325374976) (you can see the full Discord conversation there too).

If it indeed is an internal issue, can I get an ETA on a fix please? Would appreciate it.

**Comment by Neztore** [comment]
You are not handling the 'error' event. When the 'error' emission of an EventEmitter is not handled, your process will normally crash - but may not if you have any process-level error handlers. 

There may also be some issues with onJoinRequestHandle, however you must ensure the 'error' event is handled, i.e:
```js
const event = noblox.onJoinRequestHandle(config.group)
event.on("data", (...args) => onJoinRequestHandle(mongoClient, ...args))
event.on("error", e => console.error(`Error: ${e}`))
```
