### ISSUE TITLE
[BUG] 'Player not found' on getPlayerInfo

### ISSUE THREAD

**Issue by cursecodes** [noblox/noblox.js#537]
Currently, there is a bug for me that stops my ability to `getPlayerInfo`. I am using Next.js API Routes and getting the ID via `getIdFromUsername` (which is still working) and then passing it on to `getPlayerInfo`. Everything was working fine until a few days ago when it stopped working with 'Error: User does not exist'. This happens even when using `getPlayerInfo` with a hardcoded ID of 1 (Roblox official account).

**To Reproduce**
1. Create a Next.js API Route
2. Try to return `getPlayerInfo` with any ID
3. See error

**Expected behavior**
For it to return the data of the user.

Gist of code:
https://gist.github.com/cursecodes/d5c8ee7834e40c9fbd994a1ee0a9b8fe

**Comment by maccyfrog** [comment]
Updated and it works now! Thank you!

**Comment by cursecodes** [comment]
I'm on version 4.12.0. I now see that there is a newer version. Let me try that and get back to you.

**Comment by cursecodes** [comment]
It worked once I updated.
