### ISSUE TITLE
How to get chat message.

### ISSUE THREAD

**Issue by bobthedev90368** [noblox/noblox.js#538]
So Here is my code:

noblox.onNewMessage().on("data", function(data) {
        console.log("New message!", data);
        let message = noblox.getUnreadMessages([data]);
        console.log("Heres the content!", message);
       });

Essentially, I want to get the content from an unread chat message passed though the on new message function. I'm not sure how to do this.

**Comment by Aerosphia** [comment]
this is for library issues, not implementation issues. go [here](https://discord.gg/MWnz6EMSta) and ask your question in `#basic-help`
