### ISSUE TITLE
Failed to validate cookie: Are you sure the cookie is valid? Ensure you include the full cookie, including warning text.

### ISSUE THREAD

**Issue by ZeusAbarro** [noblox/noblox.js#617]
`const noblox = require('noblox.js')

async function startApp() {
  await noblox.setCookie("_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_Rest of the cookie")
  
  noblox.updateUniverse(3366664848,{ name:"Countdown To New Year"})
  
}
startApp()`

I'm trying to rename my game's name but in keeps giving me an error,I'm using replit to host it.

**Comment by Aviation-7111** [comment]
As per an update that came out a few months ago, you cookie is binded to the IP address it was created with, so using hosts like Repl.it, Glitch or Heroku will not work, as they use a different IP than what your local network hadls.

You can always host on your PC, or you can use a VPS/Dedicated Server and follow this guide, https://github.com/noblox/noblox.js/issues/545

**Comment by ZeusAbarro** [comment]
Ok,Thanks
