### ISSUE TITLE
Getting "You are not logged in" while using ROBLOXSECURITYto sign in

### ISSUE THREAD

**Issue by mehuylsharma** [noblox/noblox.js#664]
**Describe the bug**
I've got the ROBLOXSECURITY from the cookies in applications tab after logging in, and trying to use it like this:

```js
noblox.setCookie(process.env.ROBLOXSECURITY)
```
results in "you are not logged in", and does not let `noblox.sendTrade` work.

In the above have logged the env variable and that's working.

**Expected behavior**
Setting the cookie should not result in error.

**Screenshots**
![image](https://user-images.githubusercontent.com/66416012/216634259-3da84055-1d37-4ac8-8fa4-7bb8911042f9.png)

**Comment by zachariapopcorn** [comment]
What host are you using? If you're using a free host such as repl that doesn't support ssh it won't work

**Comment by mehuylsharma** [comment]
@zachariapopcorn Sorry for the late reply, I think this is using an AWS deployed server to make the call? 

Anyway this issue can be closed from my end, couldn't solve but not using roblox anymore. Thanks for the reply! :D
