### ISSUE TITLE
[BUG] No export for 'getThumbnails' module.

### ISSUE THREAD

**Issue by LuckFire** [noblox/noblox.js#677]
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

**Describe the bug**
There is no valid export for ['getThumbnails'](https://noblox.js.org/global.html#getThumbnails).
```
src/commands/test.ts:4:21 - error TS2305: Module '"noblox.js"' has no exported member 'getThumbnails'.
4 import { getAvatar, getThumbnails } from "noblox.js";
```

**To Reproduce**
Attempt to import the 'getThumbnails' module.
```ts
import { getThumbnails } from "noblox.js";
```

**Expected behavior**
The ability to use the module without it erroring.

**Screenshots**
![image](https://user-images.githubusercontent.com/39076891/221013986-c5035dac-f057-4c57-9f68-dc91c8e0f1ba.png)

**Additional context**
None.

**Comment by AxolotlMaid** [comment]
It's because noblox.js hasn't published an update to the npm package or the github releases in over a year. getThumbnails was added in May 2022 and the last publish was September 2021.

**Comment by suufi** [comment]
Has been fixed. Please update to v4.14.0.
