### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XRongo** [noblox/noblox.js#688]
Something went wrong:  TypeError: audit.data[key].created.lastIndexOf is not a f
unction
    at C:\Users\Administrator\Desktop\tpt\node_modules\noblox.js\lib\groups\onAu
ditLog.js:39:96
Something went wrong:  Error: Initialization failed: Cannot read properties of u
ndefined (reading 'latest')
    at C:\Users\Administrator\Desktop\tpt\node_modules\noblox.js\lib\util\shortP
oll.js:93:25

i am getting this error on VDS but i am not getting this error on my PC pls help me

**Comment by Neztore** [comment]
What event are you using? What parameters are you passing? Could we please get some more context than just your stacktrace, thanks.

**Comment by Neztore** [comment]
I'm now able to reproduce - any usage of onAuditLog.
