### ISSUE TITLE
Addition of Proxy Availability to Methods

### ISSUE THREAD

**Issue by nottisa** [noblox/noblox.js#709]
Ability to use proxies with commands.

Recently I was working on a small project for gathering data from Roblox users, the only issue is that the rate-limitng slows down my processes from what could be just a few seconds using proxies to 10 minutes without. Obviously, this is not super great. I don't know a whole lot about proxies and the implementation of them, but I feel like if possible, it would be a great addition to future projects who may want to gather information quickly and efficiently. I particularly would only use this for the getFreinds method as I am using the method to gather specific information about a player and figure out how much of a risk they *could* be for a game. This is all part of my master plan involving advanced anti cheat systems.

Also Unrelated, is the age function a range of the age the account could be?

**Comment by Neztore** [comment]
Proxies can be set for the Request library, which we use, through [environment variables](https://www.npmjs.com/package/request#proxies).
Request is deprecated and we plan to move away from it though, so I don't think we'll do any work in this area until we move to another method.
