### ISSUE TITLE
[BUG] uploadItem not working + response wont show item type id

### ISSUE THREAD

**Issue by ImLoadingUuU** [noblox/noblox.js#745]
**Describe the bug**
Using uploadItem wont show real item id and didnt throw any error.
and the item didnt got uploaded
**To Reproduce**
this is part of code
```js
var assetPath = req.body
            console.log(req.body)
            var path = assetPath.replace("rbxasset://", studioPath.mac); //Applications/RobloxStudio.app/Contents/Resources/Content/source/garrysmod/maps/gm_construct/amesh.mesh
            var name = path.split("/")[path.split("/").length - 1]  // File Name
            var result = await noblox.uploadItem(name,4,fs.createReadStream(path));
            console.log(result) // its 4
            res.send(result.id) // 4
            console.log("Uploaded")
```

**Comment by scandaloux** [comment]
Having same issue. Currently have to use API to get the item, really don't like it.

**Comment by naviderglol** [comment]
https://www.roblox.com/build/upload now redirects to https://create.roblox.com/dashboard/creations?activeTab=Place

seems like they've removed the legacy uploading api, waiting for a fix.

**Comment by Neztore** [comment]
Same as #681
