### ISSUE TITLE
Fix updateDeveloperProduct & addDeveloperProduct

### ISSUE THREAD

**Issue by FernandoPelarich** [noblox/noblox.js#748]
Same issue as addDeveloperProduct, which has already been fixed.
![image](https://github.com/noblox/noblox.js/assets/107149771/69cbc703-4346-4b1e-85f7-69a292f8e946)

**Comment by FernandoPelarich** [comment]
i need this fixed...

**Comment by Neztore** [comment]
> i need this fixed...

If it's already fixed for one method, why not open a pull request? That's the point of open source.

Is the fix you are referring to #751 ?

**Comment by Neztore** [comment]
Ah I see on your other issue you say you don't know JavaScript. Great place to learn. Going to merge both into this issue

**Comment by FernandoPelarich** [comment]
> > i need this fixed...
> 
> If it's already fixed for one method, why not open a pull request? That's the point of open source.
> 
> Is the fix you are referring to #751 ?

no bro, im talking about updateDeveloperProduct which uses an old roblox api. its not addDeveloerProduct, it is this one https://github.com/noblox/noblox.js/blob/master/lib/games/updateDeveloperProduct.js

**Comment by Regalijan** [comment]
Presumably fixed by #814 and #778
