### ISSUE TITLE
Dedicated API for uploading place files

### ISSUE THREAD

**Issue by scandaloux** [noblox/noblox.js#750]
Currently, I have to **overwrite** the default place file of an account using the ``uploadModel`` function. While it is sufficient, editing it's description or anything else will break it. ``uploadItem``, as of currently, seems to be broken so I haven't used that either.

As of recently, i've switched to uploading places with rbxmlx, an XML format of rblx files, but it seems like ``uploadModel`` doesn't seem to accept rbxmlx. So, now I'm stumped. I'd really not like to make my own logic for this so i'd be very nice if noblox had some support for place file uploading.

**Comment by Neztore** [comment]
Not sure what the API is for uploading places, but I suspect it is different. Could you find out what the API is?

**Comment by Neztore** [comment]
Not planned
