### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Abdjcbjc** [noblox/noblox.js#752]
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nottisa** [comment]
Please provide the details of your issue such as error codes, relevant code, etc.

**Comment by Neztore** [comment]
Closing. I have blocked you from opening issues in future.
