### ISSUE TITLE
[BUG] "Special characters" bugging out cookie.

### ISSUE THREAD

**Issue by xzzjs** [noblox/noblox.js#760]
**Describe the bug**
The bug happens on Linux using the GNU Nano Shell-based text editor. My cookie is not in the same file as the main script.
By special characters, I do not means characters essential to the cookie, I mean characters not displayed on the editor.

**To Reproduce**
1. Put your cookie in a different file
2. Save it to a variable through fs.readFileSync
3. Run it

**Expected behavior**
It should log in and proceed to execute the following code.

**Additional context**
I modified the module source directly through my "node_modules" folder. I have also opened a pull request and added the code.
PULL https://github.com/noblox/noblox.js/pull/759

**Comment by Neztore** [comment]
This looks to be to be associated with your use of readFileSync and encoding, not the library.
