### ISSUE TITLE
[BUG] addDeveloperProduct throws "Error: You are not logged in"

### ISSUE THREAD

**Issue by Ratzifutzi** [noblox/noblox.js#773]
**Describe the bug**
When using addDeveloperProduct with valid arguments and logged in account, the cookie is invalidated

**Reproduce**
1. Log in using Noblox JS API Calls with an valid cookie
2. After login, run an valid "addDeveloperProduct" Call
3. See error

**Expected behavior**
The Developer to be created returning details

**Screenshots**
![image](https://github.com/noblox/noblox.js/assets/71138238/3c4dc3a0-ed42-47bd-9220-1ed22e47b071)

**Comment by Xoltage** [comment]
im searching for a solution to this as well

**Comment by Ratzifutzi** [comment]
I figured out an solutuin: **Don't use Noblox**

I checked the source code, and the API's are completely outdated + The code is not even written correctly. The Parameters are even in the wrong order. Just use an Open Cloud API Key. It supports nearly everything.

**Comment by Xoltage** [comment]
Yeah I figured

**Comment by Xoltage** [comment]
can i create dev products with it aswell?

**Comment by Neztore** [comment]
> I figured out an solutuin: **Don't use Noblox**
> 
> I checked the source code, and the API's are completely outdated + The code is not even written correctly. The Parameters are even in the wrong order. Just use an Open Cloud API Key. It supports nearly everything.

Parameters are in the wrong order...?

Yes - Unfortunately Noblox is out of date. Please feel free to open a PR

**Comment by emsar69** [comment]
This is a bug in noblox.js. Fortunately i fixed it on my own :)

addDeveloperProduct.js:
const http = require('../util/http.js').func
const getGeneralToken = require('../util/getGeneralToken.js').func
const checkProductName = require('./checkDeveloperProductName.js').func

exports.required = ['universeId', 'name', 'priceInRobux']
exports.optional = ['description', 'jar']

// Docs
/**
 * 🔐 Create a developer product.
 * @category Game
 * @alias addDeveloperProduct
 * @param {number} universeId - The id of the universe.
 * @param {string} name - The name of the developer product.
 * @param {number} priceInRobux - The price of the product.
 * @param {string=} description - The description of the developer product.
 * @returns {Promise<DeveloperProductAddResult>}
 * @example const noblox = require("noblox.js")
 * // Login using your cookie
 * noblox.addDeveloperProduct(1, "A Developer Product", 100, "A cool item.")
**/

const nextFunction = (jar, token, universeId, name, priceInRobux, description) => {
  return checkProductName({
    universeId,
    productName: name
  }).then((exists) => {
    if (!exists) {
      return http({
        url: `//apis.roblox.com/developer-products/v1/universes/${universeId}/developerproducts?name=${name}&description=${description}&priceInRobux=${priceInRobux}`,
        options: {
          method: 'POST',
          jar: jar,
          headers: {
            'X-CSRF-TOKEN': token
          },
          resolveWithFullResponse: true
        }
      }).then((res) => {
        console.log(res)
        if (res.statusCode === 200) {
          return {
            universeId,
            name,
            priceInRobux,
            description,
            productId: typeof res.body === 'object' ? res.body.id : JSON.parse(res.body).id
          }
        } else {
          throw new Error(`Create product failed, ${res.statusCode} ${res.statusMessage}`)
        }
      })
    } else {
      throw new Error('Product with this name already exists')
    }
  })
}

exports.func = (args) => {
  const jar = args.jar

  return getGeneralToken({ jar: jar }).then((xcsrf) => {
    return nextFunction(jar, xcsrf, args.universeId, args.name, args.priceInRobux, args.description)
  })
}




checkDeveloperProductName:
const http = require('../util/http.js').func

exports.required = ['universeId', 'productName']
exports.optional = ['jar', 'productId']

// Docs
/**
 * 🔐 Check if a provided name is in use by another developer product.
 * @category Game
 * @alias checkDeveloperProductName
 * @param {number} universeId - The id of the universe.
 * @param {string} productName - The name of the developer product.
 * @param {number=} productId - The id of the developer product.
 * @returns {Promise<CheckDeveloperProductNameResult>}
 * @example const noblox = require("noblox.js")
 * // Login using your cookie
 * const productInfo = await noblox.checkDeveloperProductName(1, "A Developer Product")
**/

exports.func = (args) => {
  const jar = args.jar
  const universeId = parseInt(args.universeId) ? parseInt(args.universeId) : 0
  const productId = parseInt(args.productId) ? parseInt(args.productId) : 0

  return http({
    url: `//apis.roblox.com/developer-products/v1/universes/${universeId}/developerproducts?pageNumber=1&pageSize=2147483647`,
    options: {
      method: 'GET',
      jar: jar,
      resolveWithFullResponse: true
    }
  }).then((res) => {
    if (res.statusCode !== 200) {
      throw new Error('You are not logged in')
    } else {
      const data = JSON.parse(res.body)
      let exists = false
      data.forEach(product => {
        if(product.name == args.productName || product.id == productId){
          exists = true
          return
        }
      })
      return exists
    }
  })
}



i will report it to them tho

**Comment by Neztore** [comment]
Duplicate of #748

**Comment by Neztore** [comment]
Duplicate of #748
