### ISSUE TITLE
[BUG] cant use Add Developer Product

### ISSUE THREAD

**Issue by Xoltage** [noblox/noblox.js#776]
![image](https://github.com/noblox/noblox.js/assets/105898004/13461559-5166-4661-944e-7155fe96b5c6)

**Comment by HolyItsTio** [comment]
Heyya! Go into your node_modules/noblox.js/lib/games/addDeveloperProduct.js and just remove the checkDeveloperProduct function from there, it really doesn't need to exist and you can basically handle the error when the product already exists yourself. Np!

**Comment by Neztore** [comment]
Duplicate of #748
