### ISSUE TITLE
[BUG] Outdated API for checkDeveloperProductName.js

### ISSUE THREAD

**Issue by emsar69** [noblox/noblox.js#783]
**Describe the bug**
checkDeveloperProductName.js keep saying user not logged in.

**To Reproduce**
I fixed bug by changing module's source code and updated API

Changes I've made:
[checkDeveloperProductName.txt](https://github.com/noblox/noblox.js/files/14623354/checkDeveloperProductName.txt)
[addDeveloperProduct.txt](https://github.com/noblox/noblox.js/files/14623355/addDeveloperProduct.txt)

I appreciate to help you:)

**Comment by Neztore** [comment]
#785

**Comment by Neztore** [comment]
Duplicate of #748
