### ISSUE TITLE
Add "getUserCurrency" feature

### ISSUE THREAD

**Issue by FernandoPelarich** [noblox/noblox.js#786]
Noblox should have a getUsercurrency feature to know how much robux the user currently has

**Comment by ziad-gg** [comment]
Hello @FernandoPelarich noblox already have a function `noblox.getCurrentUser` which can return user currency

Here is the reference
https://noblox.js.org/global.html#getCurrentUser
https://noblox.js.org/global.html#LoggedInUserData

**Comment by FernandoPelarich** [comment]
Oh, I didn't know. Thanks!
