### ISSUE TITLE
[BUG] Rank Bot

### ISSUE THREAD

**Issue by KittenPixel-cell** [noblox/noblox.js#791]
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

**Describe the bug**
It keeps saying  `Failed to validate cookie: Are you sure the cookie is valid?
Ensure you include the full cookie, including warning text.`
 even tho I have the correct cookie.

PS. I do use google VPN server using open VPN as I do run a SCP: SL server on the server as well but its just noblox or aka roblox API that does not work with this.

**To Reproduce**
Use Ubuntu linux

**Expected behavior**
To working

**Screenshots**
![image](https://github.com/noblox/noblox.js/assets/79544605/e83a7c68-c2fe-4f6e-bd4c-d0e2356cbc40)

**Comment by KittenPixel-cell** [comment]
pinging roblox does not work

**Comment by KittenPixel-cell** [comment]
![image](https://github.com/noblox/noblox.js/assets/79544605/e58226a7-2ff4-405d-8f38-116a6e9bd1ab)

**Comment by Neztore** [comment]
Hello,
If you cannot ping from your server to Roblox, it is a network issue (likely related to your VPN set up) and not an issue with the Noblox library.
