### ISSUE TITLE
[BUG] configureItem() Broken | An unknown error occurred: [37] AssetIsLimited

### ISSUE THREAD

**Issue by OfficialSteam** [noblox/noblox.js#836]
### **Describe the bug**
When you attempt to use `configureItem()` it will error and say "An unknown error occurred: [37] AssetIsLimited"

### **To Reproduce**
**Steps to reproduce the behavior:**
1. Create a basic function to config a price, for example
```js
const noblox = require("noblox.js")

const newPrice = 100
const assetId = "ASSET_ID"
const assetName = "ASSET_NAME";
const description = "ASSET DESCRIPTION";

await noblox.configureItem(assetId, assetName, description, price);
```
2. Try to run it.
3. It will then error and say "An unknown error occurred: [37] AssetIsLimited" or something of the sorts.

### **Expected behavior**
I expected it to change the asset's price and not error.

### **Screenshots**
![image](https://github.com/user-attachments/assets/7f6ee770-3f4d-4ef5-872c-d92341f6bdd6)
![image](https://github.com/user-attachments/assets/a960a037-a9df-48eb-9d5a-fe0832cd94cd)

**Comment by alanbixby** [comment]
Clarification for maintainers, it is not broken, it is incompatible with post June 2024 t-shirt that go through the publishing fee workflow.

We likely should create a new endpoint that uses `itemconfiguration.`, and update this endpoint to redirect use that if they get an assetIsLimited error

**Comment by OfficialSteam** [comment]
What do you think the ETA on that is?

**Comment by forkinghell0** [comment]
Is this being worked on?

**Comment by Neztore** [comment]
Feel free to open a PR
