### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Noel3454565FNF** [noblox/noblox.js#838]
whenever i try to user noblox.getChatMessages it keep returning "you are not logged in" but the fact is I already used noblox.setCookie and even tried to full the cookie argument in the noblox.getChatMessages

--how to reproduce?--
1)set your cookie with noblox.setCookie.
2)try to use noblox.getChatMessages.

![image](https://github.com/user-attachments/assets/dd2abd40-a61e-4506-91e9-65325e50c1a9)
![image](https://github.com/user-attachments/assets/273dfd12-743c-486a-88be-7ec19c3ea79d)

**Comment by Regalijan** [comment]
We went over this in the discord server already. You do not have permissions to access conversation id 1 because your Roblox account is not part of the conversation.

That said the error handling could be improved and I'll probably work on that in the near future.
