### ISSUE TITLE
[BUG] deleteFromInventory() function Erroring.

### ISSUE THREAD

**Issue by isacxvx** [noblox/noblox.js#847]
Using the deletefrominv function will result in this error:
Uncaught SyntaxError SyntaxError: Unexpected token < in JSON at position 1
    at <anonymous> (c:directory\node_modules\noblox.js\lib\asset\deleteFromInventory.js:40:66)
    at processTicksAndRejections (<node_internals>/internal/process/task_queues:95:5)

**To Reproduce**
Setcookie to your desired cookie.
delete a owned model from your inventory.

**Expected behavior**
Deletes the model from my inventory

**Screenshots**
Errors.
![image](https://github.com/user-attachments/assets/595a93be-b384-4fce-a792-ab49ca0c3ade)

Also another thing, when using .buy, it ratelimits after 2 purchases, even if the purchases are seperated by 20 seconds.

Sorry for the blurring, the name of my folders are not very appealing.

**Comment by Regalijan** [comment]
Seems the endpoint is gone now https://devforum.roblox.com/t/official-list-of-deprecated-web-endpoints/62889/69

I'll probably open a PR for this after exams.

**Comment by Regalijan** [comment]
As for purchases, those are heavily rate limited so I'm not surprised 20 seconds isn't enough.
